### ISSUE TITLE
[BUG] Unexpected Token '.'

### ISSUE THREAD

**Issue by Najmul190** [GiorgioBrux/nitro-sniper-enhanced#101]
**I'm submitting a**
- [X] bug report
- [ ] anything else => Please do not submit support requests here. Open a discussion instead and ping me.

**I'm running**
- [X] the latest version
- [ ] anything else => Please update to the latest version and retry.

**What is the expected behavior?**
It should actually run

**What is the current behavior?**
When I try run it locally, I get the error:
```\node_modules\discord.js-light\node_modules\discord.js\src\structures\MessageEmbed.js:240
      (this.title?.length ?? 0) +
                  ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1054:16)
    at Module._compile (internal/modules/cjs/loader.js:1102:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\ashra\OneDrive\Documents\GitHub\najs-nitrosniper\node_modules\discord.js-light\node_modules\discord.js\src\structures\APIMessage.js:4:22)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)```

**Comment by GiorgioBrux** [comment]
Are you using node 14+?

**Comment by Najmul190** [comment]
> Are you using node 14+?

ah no i was using node 12, works now thanks
