### ISSUE TITLE
[BUG] uhhh help?

### ISSUE THREAD

**Issue by Voxeliorn** [GiorgioBrux/nitro-sniper-enhanced#175]
**I'm submitting a ...**
- [x] bug report
- [ ] anything else => Please do not submit support requests here. Open a discussion instead and ping me.

**I'm running**
- [x] the latest version
- [ ] anything else => Please update to the latest version and retry.

**What is the expected behavior?**
A clear and concise explanation of the expected behavior.
working?
**What is the current behavior?**
A clear and concise explanation of the current behavior.

./cmd.sh
/home/voxeliorn/Desktop/nitro-sniper-enhanced-master/src/index.js:35
const tokens = process.env.guildTokens?.split(",").filter((item) => item);
                                       ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix)
Other info if you wish.

**Comment by Voxeliorn** [comment]
oop seems like i dont have node 14 LOL
