### ISSUE TITLE
Heroku Startup failed [Log]

### ISSUE THREAD

**Issue by bonxz** [GiorgioBrux/nitro-sniper-enhanced#25]
```
2021-01-11T16:42:26.482480+00:00 heroku[worker.1]: State changed from starting to up
2021-01-11T16:42:28.274693+00:00 app[worker.1]:     _   ___ __                _____       _                   
2021-01-11T16:42:28.274722+00:00 app[worker.1]:    / | / (_) /__________     / ___/____  (_)___  ___  _____   
2021-01-11T16:42:28.274723+00:00 app[worker.1]:   /  |/ / / __/ ___/ __ \    \__ \/ __ \/ / __ \/ _ \/ ___/   
2021-01-11T16:42:28.274723+00:00 app[worker.1]:  / /|  / / /_/ /  / /_/ /   ___/ / / / / / /_/ /  __/ /       
2021-01-11T16:42:28.274723+00:00 app[worker.1]: /_/ |_/_/\__/_/_  \____/   /____/_/ /_/_/ .___/\___/_/      __
2021-01-11T16:42:28.274723+00:00 app[worker.1]:   ___  ____  / /_  ____ _____  ________/_/___/ /  ___  ____/ /
2021-01-11T16:42:28.274724+00:00 app[worker.1]:  / _ \/ __ \/ __ \/ __ `/ __ \/ ___/ _ \/ __  /  / _ \/ __  / 
2021-01-11T16:42:28.274724+00:00 app[worker.1]: /  __/ / / / / / / /_/ / / / / /__/  __/ /_/ /  /  __/ /_/ /  
2021-01-11T16:42:28.274724+00:00 app[worker.1]: \___/_/ /_/_/ /_/\__,_/_/ /_/\___/\___/\__,_/   \___/\__,_/ 
2021-01-11T16:42:28.278095+00:00 app[worker.1]: [Nitro Sniper] (INFO) Welcome!
2021-01-11T16:42:28.278538+00:00 app[worker.1]: [Nitro Sniper] (INFO) Running version 1.2.0.
2021-01-11T16:42:28.278948+00:00 app[worker.1]: [Nitro Sniper] (INFO) This program is licensed under GPL-3.0-or-later and provided free of charge at https://github.com/GiorgioBrux/nitro-sniper-enhanced.
2021-01-11T16:42:28.279654+00:00 app[worker.1]: [Nitro Sniper] (INFO) Using nitro webhook with id: [77***] and token: [***].
2021-01-11T16:42:28.280575+00:00 app[worker.1]: [Nitro Sniper] (INFO) Using notes webhook with id: [77***] and token: [***].
2021-01-11T16:42:28.289430+00:00 app[worker.1]: [Nitro Sniper] (WARNING) notesCheck is not set correctly or is undefined. Defaulting to false.
2021-01-11T16:42:29.391630+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Authorization"]
2021-01-11T16:42:29.391664+00:00 app[worker.1]:     at ClientRequest.setHeader (_http_outgoing.js:561:3)
2021-01-11T16:42:29.391665+00:00 app[worker.1]:     at Snekfetch.set (/app/node_modules/snekfetch/src/index.js:75:20)
2021-01-11T16:42:29.391665+00:00 app[worker.1]:     at APIRequest.gen (/app/node_modules/discord.js/src/client/rest/APIRequest.js:43:28)
2021-01-11T16:42:29.391666+00:00 app[worker.1]:     at /app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:59:20
2021-01-11T16:42:29.391666+00:00 app[worker.1]:     at new Promise (<anonymous>)
2021-01-11T16:42:29.391667+00:00 app[worker.1]:     at SequentialRequestHandler.execute (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:58:12)
2021-01-11T16:42:29.391667+00:00 app[worker.1]:     at SequentialRequestHandler.handle (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:125:10)
2021-01-11T16:42:29.391667+00:00 app[worker.1]:     at SequentialRequestHandler.push (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:48:10)
2021-01-11T16:42:29.391668+00:00 app[worker.1]:     at /app/node_modules/discord.js/src/client/rest/RESTManager.js:27:15
2021-01-11T16:42:29.391668+00:00 app[worker.1]:     at new Promise (<anonymous>)
2021-01-11T16:42:29.391669+00:00 app[worker.1]: (Use `node --trace-warnings ...` to show where the warning was created)
2021-01-11T16:42:29.391886+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
2021-01-11T16:42:29.392047+00:00 app[worker.1]: (node:4) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2021-01-11T16:42:44.400854+00:00 app[worker.1]: events.js:292
2021-01-11T16:42:44.400867+00:00 app[worker.1]:       throw er; // Unhandled 'error' event
2021-01-11T16:42:44.400867+00:00 app[worker.1]:       ^
2021-01-11T16:42:44.400868+00:00 app[worker.1]: 
2021-01-11T16:42:44.400868+00:00 app[worker.1]: Error: socket hang up
2021-01-11T16:42:44.400869+00:00 app[worker.1]:     at connResetException (internal/errors.js:607:14)
2021-01-11T16:42:44.400869+00:00 app[worker.1]:     at TLSSocket.socketOnEnd (_http_client.js:493:23)
2021-01-11T16:42:44.400870+00:00 app[worker.1]:     at TLSSocket.emit (events.js:327:22)
2021-01-11T16:42:44.400870+00:00 app[worker.1]:     at endReadableNT (internal/streams/readable.js:1327:12)
2021-01-11T16:42:44.400871+00:00 app[worker.1]:     at processTicksAndRejections (internal/process/task_queues.js:80:21)
2021-01-11T16:42:44.400871+00:00 app[worker.1]: Emitted 'error' event on ClientRequest instance at:
2021-01-11T16:42:44.400872+00:00 app[worker.1]:     at TLSSocket.socketOnEnd (_http_client.js:493:9)
2021-01-11T16:42:44.400872+00:00 app[worker.1]:     at TLSSocket.emit (events.js:327:22)
2021-01-11T16:42:44.400872+00:00 app[worker.1]:     at endReadableNT (internal/streams/readable.js:1327:12)
2021-01-11T16:42:44.400873+00:00 app[worker.1]:     at processTicksAndRejections (internal/process/task_queues.js:80:21) {
2021-01-11T16:42:44.400873+00:00 app[worker.1]:   code: 'ECONNRESET'
2021-01-11T16:42:44.400874+00:00 app[worker.1]: }
2021-01-11T16:42:44.459485+00:00 heroku[worker.1]: Process exited with status 1
2021-01-11T16:42:44.500087+00:00 heroku[worker.1]: State changed from up to crashed
```

Log from heroku

**Comment by GiorgioBrux** [comment]
It's the same issue of #13, you probably copy pasted the token and it also pasted a line break. Go to your heroku app, -> settings -> reveal config vars, and make sure there are no line break/spaces before the actual data.

**Comment by bonxz** [comment]
Oh yea wups.

Yes I had to redeploy the app because via Heroku CLI the update did not work correctly
