### ISSUE TITLE
Error while deploying to Heroku

### ISSUE THREAD

**Issue by jonyroda97** [GiorgioBrux/nitro-sniper-enhanced#7]
```
/app/node_modules/chalk/source/templates.js:130
		throw new Error(errMessage);
		^
 
Error: Chalk template literal is missing 1 closing bracket (`}`)
    at module.exports (/app/node_modules/chalk/source/templates.js:130:9)
    at chalkTag (/app/node_modules/chalk/source/index.js:219:9)
    at chalk.template (/app/node_modules/chalk/source/index.js:42:38)
    at Object.<anonymous> (/app/index.js:46:26)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by GiorgioBrux** [comment]
Sorry for the inconvenience, should be fixed with 861b3df.

**Comment by jonyroda97** [comment]
Is there a way to update the deployed instance or do I have to delete and create a new one?

**Comment by GiorgioBrux** [comment]
To update it, download and install the [Heroku CLI](https://devcenter.heroku.com/articles/heroku-command-line) and git, then run
- `heroku login`
- `git clone https://github.com/GiorgioBrux/nitro-sniper-enhanced.git `
- `cd nitro-sniper-enhanced`
- `git remote add heroku https://git.heroku.com/yourappname.git`
- `git push -f heroku master`

After you have this setup you can just use
- `git pull`
- `git push -f heroku master` 

Let me know if you have issues.

**Comment by jonyroda97** [comment]
New error

```
/app/node_modules/discord.js/src/client/websocket/packets/handlers/Ready.js:41
        if (!note.length) note = null;
                  ^

TypeError: Cannot read property 'length' of null
    at ReadyHandler.handle (/app/node_modules/discord.js/src/client/websocket/packets/handlers/Ready.js:41:19)
    at WebSocketPacketManager.handle (/app/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:108:65)
    at WebSocketConnection.onPacket (/app/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:336:35)
    at WebSocketConnection.onMessage (/app/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:299:17)
    at WebSocket.onMessage (/app/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (/app/node_modules/ws/lib/websocket.js:789:20)
    at Receiver.emit (events.js:315:20)
    at Receiver.dataMessage (/app/node_modules/ws/lib/receiver.js:413:14)
    at Receiver.getData (/app/node_modules/ws/lib/receiver.js:352:17)
```

**Comment by GiorgioBrux** [comment]
Should work now (it was discord.js' fault *sigh*).
If there are more errors feel free to reopen.
