### ISSUE TITLE
Can't Find File IDK

### ISSUE THREAD

**Issue by Zuessss** [GiorgioBrux/nitro-sniper-enhanced#98]
it leaves this error in repl.it

```
Error: ENOENT: no such file or directory, open '/home/runner/snipe-3/index.js'
    at Object.openSync (fs.js:462:3)
    at Object.readFileSync (fs.js:364:35)
    at Object.<anonymous> (/run_dir/interp.js:195:19)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/runner/snipe-3/index.js'
```

**Comment by GiorgioBrux** [comment]
Are you using the run button?

**Comment by nichevulcan20** [comment]
hey hey use `run` button, or i guess u messed up with packages so remake the repl but by using `import from GitHub to recover and fix all the bugs.

**Comment by GiorgioBrux** [comment]
Closing because it's stale. If someone else has the same issue please open a new one.
